// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obxwwczgxicfpufrtjzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ieHd3Y3pneGljZnB1ZnJ0anp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzM0NjYsImV4cCI6MjA3MDc0OTQ2Nn0.qAYlCF1ukvBDW8fuAh1PBRQmv3ymgKBfapT23JEbhZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});