// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vowcctjqbwndmdxfuqjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvd2NjdGpxYnduZG1keGZ1cWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTE2MTIsImV4cCI6MjA3MjMyNzYxMn0.L2yg9JPbcN-LctjAV6U_Jm6a57txonwHB1xDjmBLNQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});